/* tslint:disable */
/* eslint-disable */
/**
 * Kleister OpenAPI
 * API definition for Kleister, manage mod packs for Minecraft
 *
 * The version of the OpenAPI document: 1.0.0-alpha1
 * Contact: kleister@webhippie.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface AttachMinecraftToBuildRequest
 */
export interface AttachMinecraftToBuildRequest {
  /**
   *
   * @type {string}
   * @memberof AttachMinecraftToBuildRequest
   */
  pack: string | null;
  /**
   *
   * @type {string}
   * @memberof AttachMinecraftToBuildRequest
   */
  build: string | null;
}
