/* tslint:disable */
/* eslint-disable */
/**
 * Kleister OpenAPI
 * API definition for Kleister, manage mod packs for Minecraft
 *
 * The version of the OpenAPI document: 1.0.0-alpha1
 * Contact: kleister@webhippie.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { Fabric } from "./fabric";

/**
 * Model to represent list of fabrics
 * @export
 * @interface Fabrics
 */
export interface Fabrics {
  /**
   *
   * @type {number}
   * @memberof Fabrics
   */
  total?: number;
  /**
   *
   * @type {Array<Fabric>}
   * @memberof Fabrics
   */
  versions?: Array<Fabric>;
}
