/* tslint:disable */
/* eslint-disable */
/**
 * Kleister OpenAPI
 * API definition for Kleister, manage mod packs for Minecraft
 *
 * The version of the OpenAPI document: 1.0.0-alpha1
 * Contact: kleister@webhippie.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { Group } from "./group";
// May contain unused imports in some cases
// @ts-ignore
import type { Pack } from "./pack";

/**
 * Model to represent group pack
 * @export
 * @interface GroupPack
 */
export interface GroupPack {
  /**
   *
   * @type {string}
   * @memberof GroupPack
   */
  group_id: string;
  /**
   *
   * @type {Group}
   * @memberof GroupPack
   */
  group?: Group;
  /**
   *
   * @type {string}
   * @memberof GroupPack
   */
  pack_id: string;
  /**
   *
   * @type {Pack}
   * @memberof GroupPack
   */
  pack?: Pack;
  /**
   *
   * @type {string}
   * @memberof GroupPack
   */
  perm?: GroupPackPermEnum;
  /**
   *
   * @type {string}
   * @memberof GroupPack
   */
  created_at?: string;
  /**
   *
   * @type {string}
   * @memberof GroupPack
   */
  updated_at?: string;
}

export const GroupPackPermEnum = {
  User: "user",
  Admin: "admin",
  Owner: "owner",
} as const;

export type GroupPackPermEnum =
  (typeof GroupPackPermEnum)[keyof typeof GroupPackPermEnum];
