/* tslint:disable */
/* eslint-disable */
/**
 * Kleister OpenAPI
 * API definition for Kleister, manage mod packs for Minecraft
 *
 * The version of the OpenAPI document: 1.0.0-alpha1
 * Contact: kleister@webhippie.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { Group } from "./group";
// May contain unused imports in some cases
// @ts-ignore
import type { Mod } from "./mod";

/**
 * Model to represent group mod
 * @export
 * @interface GroupMod
 */
export interface GroupMod {
  /**
   *
   * @type {string}
   * @memberof GroupMod
   */
  group_id: string;
  /**
   *
   * @type {Group}
   * @memberof GroupMod
   */
  group?: Group;
  /**
   *
   * @type {string}
   * @memberof GroupMod
   */
  mod_id: string;
  /**
   *
   * @type {Mod}
   * @memberof GroupMod
   */
  mod?: Mod;
  /**
   *
   * @type {string}
   * @memberof GroupMod
   */
  perm?: GroupModPermEnum;
  /**
   *
   * @type {string}
   * @memberof GroupMod
   */
  created_at?: string;
  /**
   *
   * @type {string}
   * @memberof GroupMod
   */
  updated_at?: string;
}

export const GroupModPermEnum = {
  User: "user",
  Admin: "admin",
  Owner: "owner",
} as const;

export type GroupModPermEnum =
  (typeof GroupModPermEnum)[keyof typeof GroupModPermEnum];
