/* tslint:disable */
/* eslint-disable */
/**
 * Kleister OpenAPI
 * API definition for Kleister, manage mod packs for Minecraft
 *
 * The version of the OpenAPI document: 1.0.0-alpha1
 * Contact: kleister@webhippie.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { Build } from "./build";
// May contain unused imports in some cases
// @ts-ignore
import type { Forge } from "./forge";

/**
 *
 * @export
 * @interface InlineObject4
 */
export interface InlineObject4 {
  /**
   *
   * @type {number}
   * @memberof InlineObject4
   */
  total: number;
  /**
   *
   * @type {number}
   * @memberof InlineObject4
   */
  limit: number;
  /**
   *
   * @type {number}
   * @memberof InlineObject4
   */
  offset: number;
  /**
   *
   * @type {Forge}
   * @memberof InlineObject4
   */
  forge?: Forge;
  /**
   *
   * @type {Array<Build>}
   * @memberof InlineObject4
   */
  builds: Array<Build>;
}
