/* tslint:disable */
/* eslint-disable */
/**
 * Kleister OpenAPI
 * API definition for Kleister, manage mod packs for Minecraft
 *
 * The version of the OpenAPI document: 1.0.0-alpha1
 * Contact: kleister@webhippie.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { Group } from "./group";
// May contain unused imports in some cases
// @ts-ignore
import type { GroupPack } from "./group-pack";

/**
 *
 * @export
 * @interface InlineObject24
 */
export interface InlineObject24 {
  /**
   *
   * @type {number}
   * @memberof InlineObject24
   */
  total: number;
  /**
   *
   * @type {number}
   * @memberof InlineObject24
   */
  limit: number;
  /**
   *
   * @type {number}
   * @memberof InlineObject24
   */
  offset: number;
  /**
   *
   * @type {Group}
   * @memberof InlineObject24
   */
  group?: Group;
  /**
   *
   * @type {Array<GroupPack>}
   * @memberof InlineObject24
   */
  packs: Array<GroupPack>;
}
