/* tslint:disable */
/* eslint-disable */
/**
 * Kleister OpenAPI
 * API definition for Kleister, manage mod packs for Minecraft
 *
 * The version of the OpenAPI document: 1.0.0-alpha1
 * Contact: kleister@webhippie.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { User } from "./user";

/**
 *
 * @export
 * @interface InlineObject25
 */
export interface InlineObject25 {
  /**
   *
   * @type {number}
   * @memberof InlineObject25
   */
  total: number;
  /**
   *
   * @type {number}
   * @memberof InlineObject25
   */
  limit: number;
  /**
   *
   * @type {number}
   * @memberof InlineObject25
   */
  offset: number;
  /**
   *
   * @type {Array<User>}
   * @memberof InlineObject25
   */
  users: Array<User>;
}
