/* tslint:disable */
/* eslint-disable */
/**
 * Kleister OpenAPI
 * API definition for Kleister, manage mod packs for Minecraft
 *
 * The version of the OpenAPI document: 1.0.0-alpha1
 * Contact: kleister@webhippie.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { Group } from "./group";
// May contain unused imports in some cases
// @ts-ignore
import type { GroupMod } from "./group-mod";

/**
 *
 * @export
 * @interface ListGroupMods200Response
 */
export interface ListGroupMods200Response {
  /**
   *
   * @type {number}
   * @memberof ListGroupMods200Response
   */
  total: number;
  /**
   *
   * @type {number}
   * @memberof ListGroupMods200Response
   */
  limit: number;
  /**
   *
   * @type {number}
   * @memberof ListGroupMods200Response
   */
  offset: number;
  /**
   *
   * @type {Group}
   * @memberof ListGroupMods200Response
   */
  group?: Group;
  /**
   *
   * @type {Array<GroupMod>}
   * @memberof ListGroupMods200Response
   */
  mods: Array<GroupMod>;
}
