/* tslint:disable */
/* eslint-disable */
/**
 * Kleister OpenAPI
 * API definition for Kleister, manage mod packs for Minecraft
 *
 * The version of the OpenAPI document: 1.0.0-alpha1
 * Contact: kleister@webhippie.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { Pack } from "./pack";

/**
 *
 * @export
 * @interface ListPacks200Response
 */
export interface ListPacks200Response {
  /**
   *
   * @type {number}
   * @memberof ListPacks200Response
   */
  total: number;
  /**
   *
   * @type {number}
   * @memberof ListPacks200Response
   */
  limit: number;
  /**
   *
   * @type {number}
   * @memberof ListPacks200Response
   */
  offset: number;
  /**
   *
   * @type {Array<Pack>}
   * @memberof ListPacks200Response
   */
  packs: Array<Pack>;
}
