/* tslint:disable */
/* eslint-disable */
/**
 * Kleister OpenAPI
 * API definition for Kleister, manage mod packs for Minecraft
 *
 * The version of the OpenAPI document: 1.0.0-alpha1
 * Contact: kleister@webhippie.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { User } from "./user";
// May contain unused imports in some cases
// @ts-ignore
import type { UserMod } from "./user-mod";

/**
 *
 * @export
 * @interface ListUserMods200Response
 */
export interface ListUserMods200Response {
  /**
   *
   * @type {number}
   * @memberof ListUserMods200Response
   */
  total: number;
  /**
   *
   * @type {number}
   * @memberof ListUserMods200Response
   */
  limit: number;
  /**
   *
   * @type {number}
   * @memberof ListUserMods200Response
   */
  offset: number;
  /**
   *
   * @type {User}
   * @memberof ListUserMods200Response
   */
  user?: User;
  /**
   *
   * @type {Array<UserMod>}
   * @memberof ListUserMods200Response
   */
  mods: Array<UserMod>;
}
