/* tslint:disable */
/* eslint-disable */
/**
 * Kleister OpenAPI
 * API definition for Kleister, manage mod packs for Minecraft
 *
 * The version of the OpenAPI document: 1.0.0-alpha1
 * Contact: kleister@webhippie.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Model to represent pack icon
 * @export
 * @interface PackIcon
 */
export interface PackIcon {
  /**
   *
   * @type {string}
   * @memberof PackIcon
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof PackIcon
   */
  slug?: string | null;
  /**
   *
   * @type {string}
   * @memberof PackIcon
   */
  content_type?: string | null;
  /**
   *
   * @type {string}
   * @memberof PackIcon
   */
  md5?: string | null;
  /**
   *
   * @type {string}
   * @memberof PackIcon
   */
  path?: string | null;
  /**
   *
   * @type {string}
   * @memberof PackIcon
   */
  url?: string | null;
  /**
   *
   * @type {string}
   * @memberof PackIcon
   */
  upload?: string | null;
  /**
   *
   * @type {string}
   * @memberof PackIcon
   */
  created_at?: string;
  /**
   *
   * @type {string}
   * @memberof PackIcon
   */
  updated_at?: string;
}
