/* tslint:disable */
/* eslint-disable */
/**
 * Kleister OpenAPI
 * API definition for Kleister, manage mod packs for Minecraft
 *
 * The version of the OpenAPI document: 1.0.0-alpha1
 * Contact: kleister@webhippie.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { Team } from "./team";

/**
 * Model to represent list of teams
 * @export
 * @interface Teams
 */
export interface Teams {
  /**
   *
   * @type {number}
   * @memberof Teams
   */
  total?: number;
  /**
   *
   * @type {Array<Team>}
   * @memberof Teams
   */
  teams?: Array<Team>;
}
