/* tslint:disable */
/* eslint-disable */
/**
 * Kleister OpenAPI
 * API definition for Kleister, manage mod packs for Minecraft
 *
 * The version of the OpenAPI document: 1.0.0-alpha1
 * Contact: kleister@webhippie.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { Mod } from "./mod";
// May contain unused imports in some cases
// @ts-ignore
import type { Team } from "./team";

/**
 * Model to represent team mod
 * @export
 * @interface TeamMod
 */
export interface TeamMod {
  /**
   *
   * @type {string}
   * @memberof TeamMod
   */
  team_id: string;
  /**
   *
   * @type {Team}
   * @memberof TeamMod
   */
  team?: Team;
  /**
   *
   * @type {string}
   * @memberof TeamMod
   */
  mod_id: string;
  /**
   *
   * @type {Mod}
   * @memberof TeamMod
   */
  mod?: Mod;
  /**
   *
   * @type {string}
   * @memberof TeamMod
   */
  perm?: TeamModPermEnum;
  /**
   *
   * @type {string}
   * @memberof TeamMod
   */
  created_at?: string;
  /**
   *
   * @type {string}
   * @memberof TeamMod
   */
  updated_at?: string;
}

export const TeamModPermEnum = {
  Team: "team",
  Admin: "admin",
  Owner: "owner",
} as const;

export type TeamModPermEnum =
  (typeof TeamModPermEnum)[keyof typeof TeamModPermEnum];
