/* tslint:disable */
/* eslint-disable */
/**
 * Kleister OpenAPI
 * API definition for Kleister, manage mod packs for Minecraft
 *
 * The version of the OpenAPI document: 1.0.0-alpha1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UserTeamParams
 */
export interface UserTeamParams {
  /**
   *
   * @type {string}
   * @memberof UserTeamParams
   */
  team: string;
  /**
   *
   * @type {string}
   * @memberof UserTeamParams
   */
  perm: UserTeamParamsPermEnum;
}

export const UserTeamParamsPermEnum = {
  User: "user",
  Admin: "admin",
  Owner: "owner",
} as const;

export type UserTeamParamsPermEnum =
  typeof UserTeamParamsPermEnum[keyof typeof UserTeamParamsPermEnum];
