/* tslint:disable */
/* eslint-disable */
/**
 * Kleister OpenAPI
 * API definition for Kleister, manage mod packs for Minecraft
 *
 * The version of the OpenAPI document: 1.0.0-alpha1
 * Contact: kleister@webhippie.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { Team } from "./team";
// May contain unused imports in some cases
// @ts-ignore
import type { User } from "./user";

/**
 * Model to represent user team
 * @export
 * @interface UserTeam
 */
export interface UserTeam {
  /**
   *
   * @type {string}
   * @memberof UserTeam
   */
  user_id: string;
  /**
   *
   * @type {User}
   * @memberof UserTeam
   */
  user?: User;
  /**
   *
   * @type {string}
   * @memberof UserTeam
   */
  team_id: string;
  /**
   *
   * @type {Team}
   * @memberof UserTeam
   */
  team?: Team;
  /**
   *
   * @type {string}
   * @memberof UserTeam
   */
  perm?: UserTeamPermEnum;
  /**
   *
   * @type {string}
   * @memberof UserTeam
   */
  created_at?: string;
  /**
   *
   * @type {string}
   * @memberof UserTeam
   */
  updated_at?: string;
}

export const UserTeamPermEnum = {
  User: "user",
  Admin: "admin",
  Owner: "owner",
} as const;

export type UserTeamPermEnum =
  (typeof UserTeamPermEnum)[keyof typeof UserTeamPermEnum];
