/**
 * Kleister OpenAPI
 * API definition for Kleister, manage mod packs for Minecraft
 *
 * The version of the OpenAPI document: 1.0.0-alpha1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient'

/**
 * The TeamPackParams model module.
 * @module kleister/model/TeamPackParams
 * @version 1.0.0-alpha1
 */
class TeamPackParams {
  /**
     * Constructs a new <code>TeamPackParams</code>.
     * @alias module:kleister/model/TeamPackParams
     * @param team {String}
     * @param pack {String}
     * @param perm {String}
     */
  constructor (team, pack, perm) {
    TeamPackParams.initialize(this, team, pack, perm)
  }

  /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
  static initialize (obj, team, pack, perm) {
    obj['team'] = team
    obj['pack'] = pack
    obj['perm'] = perm
  }

  /**
     * Constructs a <code>TeamPackParams</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:kleister/model/TeamPackParams} obj Optional instance to populate.
     * @return {module:kleister/model/TeamPackParams} The populated <code>TeamPackParams</code> instance.
     */
  static constructFromObject (data, obj) {
    if (data) {
      obj = obj || new TeamPackParams()

      if (data.hasOwnProperty('team')) {
        obj['team'] = ApiClient.convertToType(data['team'], 'String')
      }
      if (data.hasOwnProperty('pack')) {
        obj['pack'] = ApiClient.convertToType(data['pack'], 'String')
      }
      if (data.hasOwnProperty('perm')) {
        obj['perm'] = ApiClient.convertToType(data['perm'], 'String')
      }
    }
    return obj
  }
}

/**
 * @member {String} team
 */
TeamPackParams.prototype['team'] = undefined

/**
 * @member {String} pack
 */
TeamPackParams.prototype['pack'] = undefined

/**
 * @member {String} perm
 */
TeamPackParams.prototype['perm'] = undefined

export default TeamPackParams
