/**
 * Kleister OpenAPI
 * API definition for Kleister, manage mod packs for Minecraft
 *
 * The version of the OpenAPI document: 1.0.0-alpha1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient'

/**
 * The UserPack model module.
 * @module kleister/model/UserPack
 * @version 1.0.0-alpha1
 */
class UserPack {
  /**
     * Constructs a new <code>UserPack</code>.
     * @alias module:kleister/model/UserPack
     * @param userId {String}
     * @param packId {String}
     * @param perm {String}
     */
  constructor (userId, packId, perm) {
    UserPack.initialize(this, userId, packId, perm)
  }

  /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
  static initialize (obj, userId, packId, perm) {
    obj['user_id'] = userId
    obj['pack_id'] = packId
    obj['perm'] = perm
  }

  /**
     * Constructs a <code>UserPack</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:kleister/model/UserPack} obj Optional instance to populate.
     * @return {module:kleister/model/UserPack} The populated <code>UserPack</code> instance.
     */
  static constructFromObject (data, obj) {
    if (data) {
      obj = obj || new UserPack()

      if (data.hasOwnProperty('user_id')) {
        obj['user_id'] = ApiClient.convertToType(data['user_id'], 'String')
      }
      if (data.hasOwnProperty('pack_id')) {
        obj['pack_id'] = ApiClient.convertToType(data['pack_id'], 'String')
      }
      if (data.hasOwnProperty('perm')) {
        obj['perm'] = ApiClient.convertToType(data['perm'], 'String')
      }
    }
    return obj
  }
}

/**
 * @member {String} user_id
 */
UserPack.prototype['user_id'] = undefined

/**
 * @member {String} pack_id
 */
UserPack.prototype['pack_id'] = undefined

/**
 * @member {String} perm
 */
UserPack.prototype['perm'] = undefined

export default UserPack
