/* tslint:disable */
/* eslint-disable */
/**
 * Kleister OpenAPI
 * API definition for Kleister, manage mod packs for Minecraft
 *
 * The version of the OpenAPI document: 1.0.0-alpha1
 * Contact: kleister@webhippie.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from "../configuration";
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from "axios";
import globalAxios from "axios";
// URLSearchParams not necessarily used
// @ts-ignore
import { URL, URLSearchParams } from "url";
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from "../common";
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  type RequestArgs,
  BaseAPI,
  RequiredError,
  operationServerMap,
} from "../base";
// @ts-ignore
import type { CreateGroupRequest } from "../model";
// @ts-ignore
import type { DeleteGroupFromModRequest } from "../model";
// @ts-ignore
import type { DeleteGroupFromPackRequest } from "../model";
// @ts-ignore
import type { DeletePackFromUserRequest } from "../model";
// @ts-ignore
import type { Group } from "../model";
// @ts-ignore
import type { ListGroupMods200Response } from "../model";
// @ts-ignore
import type { ListGroupPacks200Response } from "../model";
// @ts-ignore
import type { ListGroupUsers200Response } from "../model";
// @ts-ignore
import type { ListGroups200Response } from "../model";
// @ts-ignore
import type { Notification } from "../model";
// @ts-ignore
import type { PermitGroupModRequest } from "../model";
// @ts-ignore
import type { PermitGroupPackRequest } from "../model";
// @ts-ignore
import type { PermitPackUserRequest } from "../model";
/**
 * GroupApi - axios parameter creator
 * @export
 */
export const GroupApiAxiosParamCreator = function (
  configuration?: Configuration,
) {
  return {
    /**
     *
     * @summary Attach a mod to group
     * @param {string} groupId A group identifier or slug
     * @param {PermitGroupModRequest} permitGroupModRequest The group mod data to permit
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    attachGroupToMod: async (
      groupId: string,
      permitGroupModRequest: PermitGroupModRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'groupId' is not null or undefined
      assertParamExists("attachGroupToMod", "groupId", groupId);
      // verify required parameter 'permitGroupModRequest' is not null or undefined
      assertParamExists(
        "attachGroupToMod",
        "permitGroupModRequest",
        permitGroupModRequest,
      );
      const localVarPath = `/groups/{group_id}/mods`.replace(
        `{${"group_id"}}`,
        encodeURIComponent(String(groupId)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication Basic required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication Header required
      await setApiKeyToObject(
        localVarHeaderParameter,
        "X-API-Key",
        configuration,
      );

      // authentication Bearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        permitGroupModRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Attach a pack to group
     * @param {string} groupId A group identifier or slug
     * @param {PermitGroupPackRequest} permitGroupPackRequest The group pack data to permit
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    attachGroupToPack: async (
      groupId: string,
      permitGroupPackRequest: PermitGroupPackRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'groupId' is not null or undefined
      assertParamExists("attachGroupToPack", "groupId", groupId);
      // verify required parameter 'permitGroupPackRequest' is not null or undefined
      assertParamExists(
        "attachGroupToPack",
        "permitGroupPackRequest",
        permitGroupPackRequest,
      );
      const localVarPath = `/groups/{group_id}/packs`.replace(
        `{${"group_id"}}`,
        encodeURIComponent(String(groupId)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication Basic required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication Header required
      await setApiKeyToObject(
        localVarHeaderParameter,
        "X-API-Key",
        configuration,
      );

      // authentication Bearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        permitGroupPackRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Attach a user to group
     * @param {string} groupId A group identifier or slug
     * @param {PermitPackUserRequest} permitPackUserRequest The group user data to permit
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    attachGroupToUser: async (
      groupId: string,
      permitPackUserRequest: PermitPackUserRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'groupId' is not null or undefined
      assertParamExists("attachGroupToUser", "groupId", groupId);
      // verify required parameter 'permitPackUserRequest' is not null or undefined
      assertParamExists(
        "attachGroupToUser",
        "permitPackUserRequest",
        permitPackUserRequest,
      );
      const localVarPath = `/groups/{group_id}/users`.replace(
        `{${"group_id"}}`,
        encodeURIComponent(String(groupId)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication Basic required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication Header required
      await setApiKeyToObject(
        localVarHeaderParameter,
        "X-API-Key",
        configuration,
      );

      // authentication Bearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        permitPackUserRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Create a new group
     * @param {CreateGroupRequest} createGroupRequest The group data to create
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createGroup: async (
      createGroupRequest: CreateGroupRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'createGroupRequest' is not null or undefined
      assertParamExists(
        "createGroup",
        "createGroupRequest",
        createGroupRequest,
      );
      const localVarPath = `/groups`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication Basic required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication Header required
      await setApiKeyToObject(
        localVarHeaderParameter,
        "X-API-Key",
        configuration,
      );

      // authentication Bearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        createGroupRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Delete a specific group
     * @param {string} groupId A group identifier or slug
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteGroup: async (
      groupId: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'groupId' is not null or undefined
      assertParamExists("deleteGroup", "groupId", groupId);
      const localVarPath = `/groups/{group_id}`.replace(
        `{${"group_id"}}`,
        encodeURIComponent(String(groupId)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "DELETE",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication Basic required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication Header required
      await setApiKeyToObject(
        localVarHeaderParameter,
        "X-API-Key",
        configuration,
      );

      // authentication Bearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Unlink a mod from group
     * @param {string} groupId A group identifier or slug
     * @param {DeleteGroupFromModRequest} deleteGroupFromModRequest The group mod data to unlink
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteGroupFromMod: async (
      groupId: string,
      deleteGroupFromModRequest: DeleteGroupFromModRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'groupId' is not null or undefined
      assertParamExists("deleteGroupFromMod", "groupId", groupId);
      // verify required parameter 'deleteGroupFromModRequest' is not null or undefined
      assertParamExists(
        "deleteGroupFromMod",
        "deleteGroupFromModRequest",
        deleteGroupFromModRequest,
      );
      const localVarPath = `/groups/{group_id}/mods`.replace(
        `{${"group_id"}}`,
        encodeURIComponent(String(groupId)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "DELETE",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication Basic required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication Header required
      await setApiKeyToObject(
        localVarHeaderParameter,
        "X-API-Key",
        configuration,
      );

      // authentication Bearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        deleteGroupFromModRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Unlink a pack from group
     * @param {string} groupId A group identifier or slug
     * @param {DeleteGroupFromPackRequest} deleteGroupFromPackRequest The group pack data to unlink
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteGroupFromPack: async (
      groupId: string,
      deleteGroupFromPackRequest: DeleteGroupFromPackRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'groupId' is not null or undefined
      assertParamExists("deleteGroupFromPack", "groupId", groupId);
      // verify required parameter 'deleteGroupFromPackRequest' is not null or undefined
      assertParamExists(
        "deleteGroupFromPack",
        "deleteGroupFromPackRequest",
        deleteGroupFromPackRequest,
      );
      const localVarPath = `/groups/{group_id}/packs`.replace(
        `{${"group_id"}}`,
        encodeURIComponent(String(groupId)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "DELETE",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication Basic required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication Header required
      await setApiKeyToObject(
        localVarHeaderParameter,
        "X-API-Key",
        configuration,
      );

      // authentication Bearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        deleteGroupFromPackRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Unlink a user from group
     * @param {string} groupId A group identifier or slug
     * @param {DeletePackFromUserRequest} deletePackFromUserRequest The group user data to unlink
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteGroupFromUser: async (
      groupId: string,
      deletePackFromUserRequest: DeletePackFromUserRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'groupId' is not null or undefined
      assertParamExists("deleteGroupFromUser", "groupId", groupId);
      // verify required parameter 'deletePackFromUserRequest' is not null or undefined
      assertParamExists(
        "deleteGroupFromUser",
        "deletePackFromUserRequest",
        deletePackFromUserRequest,
      );
      const localVarPath = `/groups/{group_id}/users`.replace(
        `{${"group_id"}}`,
        encodeURIComponent(String(groupId)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "DELETE",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication Basic required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication Header required
      await setApiKeyToObject(
        localVarHeaderParameter,
        "X-API-Key",
        configuration,
      );

      // authentication Bearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        deletePackFromUserRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Fetch all mods attached to group
     * @param {string} groupId A group identifier or slug
     * @param {string} [search] Search query
     * @param {string} [sort] Sorting column
     * @param {ListGroupModsOrderEnum} [order] Sorting order
     * @param {number} [limit] Paging limit
     * @param {number} [offset] Paging offset
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listGroupMods: async (
      groupId: string,
      search?: string,
      sort?: string,
      order?: ListGroupModsOrderEnum,
      limit?: number,
      offset?: number,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'groupId' is not null or undefined
      assertParamExists("listGroupMods", "groupId", groupId);
      const localVarPath = `/groups/{group_id}/mods`.replace(
        `{${"group_id"}}`,
        encodeURIComponent(String(groupId)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication Basic required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication Header required
      await setApiKeyToObject(
        localVarHeaderParameter,
        "X-API-Key",
        configuration,
      );

      // authentication Bearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      if (search !== undefined) {
        localVarQueryParameter["search"] = search;
      }

      if (sort !== undefined) {
        localVarQueryParameter["sort"] = sort;
      }

      if (order !== undefined) {
        localVarQueryParameter["order"] = order;
      }

      if (limit !== undefined) {
        localVarQueryParameter["limit"] = limit;
      }

      if (offset !== undefined) {
        localVarQueryParameter["offset"] = offset;
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Fetch all packs attached to group
     * @param {string} groupId A group identifier or slug
     * @param {string} [search] Search query
     * @param {string} [sort] Sorting column
     * @param {ListGroupPacksOrderEnum} [order] Sorting order
     * @param {number} [limit] Paging limit
     * @param {number} [offset] Paging offset
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listGroupPacks: async (
      groupId: string,
      search?: string,
      sort?: string,
      order?: ListGroupPacksOrderEnum,
      limit?: number,
      offset?: number,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'groupId' is not null or undefined
      assertParamExists("listGroupPacks", "groupId", groupId);
      const localVarPath = `/groups/{group_id}/packs`.replace(
        `{${"group_id"}}`,
        encodeURIComponent(String(groupId)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication Basic required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication Header required
      await setApiKeyToObject(
        localVarHeaderParameter,
        "X-API-Key",
        configuration,
      );

      // authentication Bearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      if (search !== undefined) {
        localVarQueryParameter["search"] = search;
      }

      if (sort !== undefined) {
        localVarQueryParameter["sort"] = sort;
      }

      if (order !== undefined) {
        localVarQueryParameter["order"] = order;
      }

      if (limit !== undefined) {
        localVarQueryParameter["limit"] = limit;
      }

      if (offset !== undefined) {
        localVarQueryParameter["offset"] = offset;
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Fetch all users attached to group
     * @param {string} groupId A group identifier or slug
     * @param {string} [search] Search query
     * @param {string} [sort] Sorting column
     * @param {ListGroupUsersOrderEnum} [order] Sorting order
     * @param {number} [limit] Paging limit
     * @param {number} [offset] Paging offset
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listGroupUsers: async (
      groupId: string,
      search?: string,
      sort?: string,
      order?: ListGroupUsersOrderEnum,
      limit?: number,
      offset?: number,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'groupId' is not null or undefined
      assertParamExists("listGroupUsers", "groupId", groupId);
      const localVarPath = `/groups/{group_id}/users`.replace(
        `{${"group_id"}}`,
        encodeURIComponent(String(groupId)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication Basic required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication Header required
      await setApiKeyToObject(
        localVarHeaderParameter,
        "X-API-Key",
        configuration,
      );

      // authentication Bearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      if (search !== undefined) {
        localVarQueryParameter["search"] = search;
      }

      if (sort !== undefined) {
        localVarQueryParameter["sort"] = sort;
      }

      if (order !== undefined) {
        localVarQueryParameter["order"] = order;
      }

      if (limit !== undefined) {
        localVarQueryParameter["limit"] = limit;
      }

      if (offset !== undefined) {
        localVarQueryParameter["offset"] = offset;
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Fetch all available groups
     * @param {string} [search] Search query
     * @param {string} [sort] Sorting column
     * @param {ListGroupsOrderEnum} [order] Sorting order
     * @param {number} [limit] Paging limit
     * @param {number} [offset] Paging offset
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listGroups: async (
      search?: string,
      sort?: string,
      order?: ListGroupsOrderEnum,
      limit?: number,
      offset?: number,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/groups`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication Basic required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication Header required
      await setApiKeyToObject(
        localVarHeaderParameter,
        "X-API-Key",
        configuration,
      );

      // authentication Bearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      if (search !== undefined) {
        localVarQueryParameter["search"] = search;
      }

      if (sort !== undefined) {
        localVarQueryParameter["sort"] = sort;
      }

      if (order !== undefined) {
        localVarQueryParameter["order"] = order;
      }

      if (limit !== undefined) {
        localVarQueryParameter["limit"] = limit;
      }

      if (offset !== undefined) {
        localVarQueryParameter["offset"] = offset;
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Update mod perms for group
     * @param {string} groupId A group identifier or slug
     * @param {PermitGroupModRequest} permitGroupModRequest The group mod data to permit
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    permitGroupMod: async (
      groupId: string,
      permitGroupModRequest: PermitGroupModRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'groupId' is not null or undefined
      assertParamExists("permitGroupMod", "groupId", groupId);
      // verify required parameter 'permitGroupModRequest' is not null or undefined
      assertParamExists(
        "permitGroupMod",
        "permitGroupModRequest",
        permitGroupModRequest,
      );
      const localVarPath = `/groups/{group_id}/mods`.replace(
        `{${"group_id"}}`,
        encodeURIComponent(String(groupId)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "PUT",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication Basic required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication Header required
      await setApiKeyToObject(
        localVarHeaderParameter,
        "X-API-Key",
        configuration,
      );

      // authentication Bearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        permitGroupModRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Update pack perms for group
     * @param {string} groupId A group identifier or slug
     * @param {PermitGroupPackRequest} permitGroupPackRequest The group pack data to permit
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    permitGroupPack: async (
      groupId: string,
      permitGroupPackRequest: PermitGroupPackRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'groupId' is not null or undefined
      assertParamExists("permitGroupPack", "groupId", groupId);
      // verify required parameter 'permitGroupPackRequest' is not null or undefined
      assertParamExists(
        "permitGroupPack",
        "permitGroupPackRequest",
        permitGroupPackRequest,
      );
      const localVarPath = `/groups/{group_id}/packs`.replace(
        `{${"group_id"}}`,
        encodeURIComponent(String(groupId)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "PUT",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication Basic required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication Header required
      await setApiKeyToObject(
        localVarHeaderParameter,
        "X-API-Key",
        configuration,
      );

      // authentication Bearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        permitGroupPackRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Update user perms for group
     * @param {string} groupId A group identifier or slug
     * @param {PermitPackUserRequest} permitPackUserRequest The group user data to permit
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    permitGroupUser: async (
      groupId: string,
      permitPackUserRequest: PermitPackUserRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'groupId' is not null or undefined
      assertParamExists("permitGroupUser", "groupId", groupId);
      // verify required parameter 'permitPackUserRequest' is not null or undefined
      assertParamExists(
        "permitGroupUser",
        "permitPackUserRequest",
        permitPackUserRequest,
      );
      const localVarPath = `/groups/{group_id}/users`.replace(
        `{${"group_id"}}`,
        encodeURIComponent(String(groupId)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "PUT",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication Basic required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication Header required
      await setApiKeyToObject(
        localVarHeaderParameter,
        "X-API-Key",
        configuration,
      );

      // authentication Bearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        permitPackUserRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Fetch a specific group
     * @param {string} groupId A group identifier or slug
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    showGroup: async (
      groupId: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'groupId' is not null or undefined
      assertParamExists("showGroup", "groupId", groupId);
      const localVarPath = `/groups/{group_id}`.replace(
        `{${"group_id"}}`,
        encodeURIComponent(String(groupId)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication Basic required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication Header required
      await setApiKeyToObject(
        localVarHeaderParameter,
        "X-API-Key",
        configuration,
      );

      // authentication Bearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary Update a specific group
     * @param {string} groupId A group identifier or slug
     * @param {CreateGroupRequest} createGroupRequest The group data to update
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateGroup: async (
      groupId: string,
      createGroupRequest: CreateGroupRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'groupId' is not null or undefined
      assertParamExists("updateGroup", "groupId", groupId);
      // verify required parameter 'createGroupRequest' is not null or undefined
      assertParamExists(
        "updateGroup",
        "createGroupRequest",
        createGroupRequest,
      );
      const localVarPath = `/groups/{group_id}`.replace(
        `{${"group_id"}}`,
        encodeURIComponent(String(groupId)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "PUT",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication Basic required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration);

      // authentication Header required
      await setApiKeyToObject(
        localVarHeaderParameter,
        "X-API-Key",
        configuration,
      );

      // authentication Bearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        createGroupRequest,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * GroupApi - functional programming interface
 * @export
 */
export const GroupApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = GroupApiAxiosParamCreator(configuration);
  return {
    /**
     *
     * @summary Attach a mod to group
     * @param {string} groupId A group identifier or slug
     * @param {PermitGroupModRequest} permitGroupModRequest The group mod data to permit
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async attachGroupToMod(
      groupId: string,
      permitGroupModRequest: PermitGroupModRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Notification>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.attachGroupToMod(
          groupId,
          permitGroupModRequest,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["GroupApi.attachGroupToMod"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Attach a pack to group
     * @param {string} groupId A group identifier or slug
     * @param {PermitGroupPackRequest} permitGroupPackRequest The group pack data to permit
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async attachGroupToPack(
      groupId: string,
      permitGroupPackRequest: PermitGroupPackRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Notification>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.attachGroupToPack(
          groupId,
          permitGroupPackRequest,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["GroupApi.attachGroupToPack"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Attach a user to group
     * @param {string} groupId A group identifier or slug
     * @param {PermitPackUserRequest} permitPackUserRequest The group user data to permit
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async attachGroupToUser(
      groupId: string,
      permitPackUserRequest: PermitPackUserRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Notification>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.attachGroupToUser(
          groupId,
          permitPackUserRequest,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["GroupApi.attachGroupToUser"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Create a new group
     * @param {CreateGroupRequest} createGroupRequest The group data to create
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async createGroup(
      createGroupRequest: CreateGroupRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Group>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.createGroup(
        createGroupRequest,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["GroupApi.createGroup"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Delete a specific group
     * @param {string} groupId A group identifier or slug
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async deleteGroup(
      groupId: string,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Notification>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.deleteGroup(
        groupId,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["GroupApi.deleteGroup"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Unlink a mod from group
     * @param {string} groupId A group identifier or slug
     * @param {DeleteGroupFromModRequest} deleteGroupFromModRequest The group mod data to unlink
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async deleteGroupFromMod(
      groupId: string,
      deleteGroupFromModRequest: DeleteGroupFromModRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Notification>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.deleteGroupFromMod(
          groupId,
          deleteGroupFromModRequest,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["GroupApi.deleteGroupFromMod"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Unlink a pack from group
     * @param {string} groupId A group identifier or slug
     * @param {DeleteGroupFromPackRequest} deleteGroupFromPackRequest The group pack data to unlink
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async deleteGroupFromPack(
      groupId: string,
      deleteGroupFromPackRequest: DeleteGroupFromPackRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Notification>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.deleteGroupFromPack(
          groupId,
          deleteGroupFromPackRequest,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["GroupApi.deleteGroupFromPack"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Unlink a user from group
     * @param {string} groupId A group identifier or slug
     * @param {DeletePackFromUserRequest} deletePackFromUserRequest The group user data to unlink
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async deleteGroupFromUser(
      groupId: string,
      deletePackFromUserRequest: DeletePackFromUserRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Notification>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.deleteGroupFromUser(
          groupId,
          deletePackFromUserRequest,
          options,
        );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["GroupApi.deleteGroupFromUser"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Fetch all mods attached to group
     * @param {string} groupId A group identifier or slug
     * @param {string} [search] Search query
     * @param {string} [sort] Sorting column
     * @param {ListGroupModsOrderEnum} [order] Sorting order
     * @param {number} [limit] Paging limit
     * @param {number} [offset] Paging offset
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async listGroupMods(
      groupId: string,
      search?: string,
      sort?: string,
      order?: ListGroupModsOrderEnum,
      limit?: number,
      offset?: number,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<ListGroupMods200Response>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.listGroupMods(
        groupId,
        search,
        sort,
        order,
        limit,
        offset,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["GroupApi.listGroupMods"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Fetch all packs attached to group
     * @param {string} groupId A group identifier or slug
     * @param {string} [search] Search query
     * @param {string} [sort] Sorting column
     * @param {ListGroupPacksOrderEnum} [order] Sorting order
     * @param {number} [limit] Paging limit
     * @param {number} [offset] Paging offset
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async listGroupPacks(
      groupId: string,
      search?: string,
      sort?: string,
      order?: ListGroupPacksOrderEnum,
      limit?: number,
      offset?: number,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<ListGroupPacks200Response>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.listGroupPacks(
        groupId,
        search,
        sort,
        order,
        limit,
        offset,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["GroupApi.listGroupPacks"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Fetch all users attached to group
     * @param {string} groupId A group identifier or slug
     * @param {string} [search] Search query
     * @param {string} [sort] Sorting column
     * @param {ListGroupUsersOrderEnum} [order] Sorting order
     * @param {number} [limit] Paging limit
     * @param {number} [offset] Paging offset
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async listGroupUsers(
      groupId: string,
      search?: string,
      sort?: string,
      order?: ListGroupUsersOrderEnum,
      limit?: number,
      offset?: number,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<ListGroupUsers200Response>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.listGroupUsers(
        groupId,
        search,
        sort,
        order,
        limit,
        offset,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["GroupApi.listGroupUsers"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Fetch all available groups
     * @param {string} [search] Search query
     * @param {string} [sort] Sorting column
     * @param {ListGroupsOrderEnum} [order] Sorting order
     * @param {number} [limit] Paging limit
     * @param {number} [offset] Paging offset
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async listGroups(
      search?: string,
      sort?: string,
      order?: ListGroupsOrderEnum,
      limit?: number,
      offset?: number,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<ListGroups200Response>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.listGroups(
        search,
        sort,
        order,
        limit,
        offset,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["GroupApi.listGroups"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Update mod perms for group
     * @param {string} groupId A group identifier or slug
     * @param {PermitGroupModRequest} permitGroupModRequest The group mod data to permit
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async permitGroupMod(
      groupId: string,
      permitGroupModRequest: PermitGroupModRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Notification>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.permitGroupMod(
        groupId,
        permitGroupModRequest,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["GroupApi.permitGroupMod"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Update pack perms for group
     * @param {string} groupId A group identifier or slug
     * @param {PermitGroupPackRequest} permitGroupPackRequest The group pack data to permit
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async permitGroupPack(
      groupId: string,
      permitGroupPackRequest: PermitGroupPackRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Notification>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.permitGroupPack(
        groupId,
        permitGroupPackRequest,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["GroupApi.permitGroupPack"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Update user perms for group
     * @param {string} groupId A group identifier or slug
     * @param {PermitPackUserRequest} permitPackUserRequest The group user data to permit
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async permitGroupUser(
      groupId: string,
      permitPackUserRequest: PermitPackUserRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Notification>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.permitGroupUser(
        groupId,
        permitPackUserRequest,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["GroupApi.permitGroupUser"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Fetch a specific group
     * @param {string} groupId A group identifier or slug
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async showGroup(
      groupId: string,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Group>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.showGroup(
        groupId,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["GroupApi.showGroup"]?.[localVarOperationServerIndex]
          ?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary Update a specific group
     * @param {string} groupId A group identifier or slug
     * @param {CreateGroupRequest} createGroupRequest The group data to update
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async updateGroup(
      groupId: string,
      createGroupRequest: CreateGroupRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Group>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.updateGroup(
        groupId,
        createGroupRequest,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap["GroupApi.updateGroup"]?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * GroupApi - factory interface
 * @export
 */
export const GroupApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = GroupApiFp(configuration);
  return {
    /**
     *
     * @summary Attach a mod to group
     * @param {GroupApiAttachGroupToModRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    attachGroupToMod(
      requestParameters: GroupApiAttachGroupToModRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<Notification> {
      return localVarFp
        .attachGroupToMod(
          requestParameters.groupId,
          requestParameters.permitGroupModRequest,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Attach a pack to group
     * @param {GroupApiAttachGroupToPackRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    attachGroupToPack(
      requestParameters: GroupApiAttachGroupToPackRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<Notification> {
      return localVarFp
        .attachGroupToPack(
          requestParameters.groupId,
          requestParameters.permitGroupPackRequest,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Attach a user to group
     * @param {GroupApiAttachGroupToUserRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    attachGroupToUser(
      requestParameters: GroupApiAttachGroupToUserRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<Notification> {
      return localVarFp
        .attachGroupToUser(
          requestParameters.groupId,
          requestParameters.permitPackUserRequest,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Create a new group
     * @param {GroupApiCreateGroupRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createGroup(
      requestParameters: GroupApiCreateGroupRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<Group> {
      return localVarFp
        .createGroup(requestParameters.createGroupRequest, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Delete a specific group
     * @param {GroupApiDeleteGroupRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteGroup(
      requestParameters: GroupApiDeleteGroupRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<Notification> {
      return localVarFp
        .deleteGroup(requestParameters.groupId, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Unlink a mod from group
     * @param {GroupApiDeleteGroupFromModRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteGroupFromMod(
      requestParameters: GroupApiDeleteGroupFromModRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<Notification> {
      return localVarFp
        .deleteGroupFromMod(
          requestParameters.groupId,
          requestParameters.deleteGroupFromModRequest,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Unlink a pack from group
     * @param {GroupApiDeleteGroupFromPackRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteGroupFromPack(
      requestParameters: GroupApiDeleteGroupFromPackRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<Notification> {
      return localVarFp
        .deleteGroupFromPack(
          requestParameters.groupId,
          requestParameters.deleteGroupFromPackRequest,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Unlink a user from group
     * @param {GroupApiDeleteGroupFromUserRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteGroupFromUser(
      requestParameters: GroupApiDeleteGroupFromUserRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<Notification> {
      return localVarFp
        .deleteGroupFromUser(
          requestParameters.groupId,
          requestParameters.deletePackFromUserRequest,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Fetch all mods attached to group
     * @param {GroupApiListGroupModsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listGroupMods(
      requestParameters: GroupApiListGroupModsRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<ListGroupMods200Response> {
      return localVarFp
        .listGroupMods(
          requestParameters.groupId,
          requestParameters.search,
          requestParameters.sort,
          requestParameters.order,
          requestParameters.limit,
          requestParameters.offset,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Fetch all packs attached to group
     * @param {GroupApiListGroupPacksRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listGroupPacks(
      requestParameters: GroupApiListGroupPacksRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<ListGroupPacks200Response> {
      return localVarFp
        .listGroupPacks(
          requestParameters.groupId,
          requestParameters.search,
          requestParameters.sort,
          requestParameters.order,
          requestParameters.limit,
          requestParameters.offset,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Fetch all users attached to group
     * @param {GroupApiListGroupUsersRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listGroupUsers(
      requestParameters: GroupApiListGroupUsersRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<ListGroupUsers200Response> {
      return localVarFp
        .listGroupUsers(
          requestParameters.groupId,
          requestParameters.search,
          requestParameters.sort,
          requestParameters.order,
          requestParameters.limit,
          requestParameters.offset,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Fetch all available groups
     * @param {GroupApiListGroupsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listGroups(
      requestParameters: GroupApiListGroupsRequest = {},
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<ListGroups200Response> {
      return localVarFp
        .listGroups(
          requestParameters.search,
          requestParameters.sort,
          requestParameters.order,
          requestParameters.limit,
          requestParameters.offset,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Update mod perms for group
     * @param {GroupApiPermitGroupModRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    permitGroupMod(
      requestParameters: GroupApiPermitGroupModRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<Notification> {
      return localVarFp
        .permitGroupMod(
          requestParameters.groupId,
          requestParameters.permitGroupModRequest,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Update pack perms for group
     * @param {GroupApiPermitGroupPackRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    permitGroupPack(
      requestParameters: GroupApiPermitGroupPackRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<Notification> {
      return localVarFp
        .permitGroupPack(
          requestParameters.groupId,
          requestParameters.permitGroupPackRequest,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Update user perms for group
     * @param {GroupApiPermitGroupUserRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    permitGroupUser(
      requestParameters: GroupApiPermitGroupUserRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<Notification> {
      return localVarFp
        .permitGroupUser(
          requestParameters.groupId,
          requestParameters.permitPackUserRequest,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Fetch a specific group
     * @param {GroupApiShowGroupRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    showGroup(
      requestParameters: GroupApiShowGroupRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<Group> {
      return localVarFp
        .showGroup(requestParameters.groupId, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary Update a specific group
     * @param {GroupApiUpdateGroupRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateGroup(
      requestParameters: GroupApiUpdateGroupRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<Group> {
      return localVarFp
        .updateGroup(
          requestParameters.groupId,
          requestParameters.createGroupRequest,
          options,
        )
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * Request parameters for attachGroupToMod operation in GroupApi.
 * @export
 * @interface GroupApiAttachGroupToModRequest
 */
export interface GroupApiAttachGroupToModRequest {
  /**
   * A group identifier or slug
   * @type {string}
   * @memberof GroupApiAttachGroupToMod
   */
  readonly groupId: string;

  /**
   * The group mod data to permit
   * @type {PermitGroupModRequest}
   * @memberof GroupApiAttachGroupToMod
   */
  readonly permitGroupModRequest: PermitGroupModRequest;
}

/**
 * Request parameters for attachGroupToPack operation in GroupApi.
 * @export
 * @interface GroupApiAttachGroupToPackRequest
 */
export interface GroupApiAttachGroupToPackRequest {
  /**
   * A group identifier or slug
   * @type {string}
   * @memberof GroupApiAttachGroupToPack
   */
  readonly groupId: string;

  /**
   * The group pack data to permit
   * @type {PermitGroupPackRequest}
   * @memberof GroupApiAttachGroupToPack
   */
  readonly permitGroupPackRequest: PermitGroupPackRequest;
}

/**
 * Request parameters for attachGroupToUser operation in GroupApi.
 * @export
 * @interface GroupApiAttachGroupToUserRequest
 */
export interface GroupApiAttachGroupToUserRequest {
  /**
   * A group identifier or slug
   * @type {string}
   * @memberof GroupApiAttachGroupToUser
   */
  readonly groupId: string;

  /**
   * The group user data to permit
   * @type {PermitPackUserRequest}
   * @memberof GroupApiAttachGroupToUser
   */
  readonly permitPackUserRequest: PermitPackUserRequest;
}

/**
 * Request parameters for createGroup operation in GroupApi.
 * @export
 * @interface GroupApiCreateGroupRequest
 */
export interface GroupApiCreateGroupRequest {
  /**
   * The group data to create
   * @type {CreateGroupRequest}
   * @memberof GroupApiCreateGroup
   */
  readonly createGroupRequest: CreateGroupRequest;
}

/**
 * Request parameters for deleteGroup operation in GroupApi.
 * @export
 * @interface GroupApiDeleteGroupRequest
 */
export interface GroupApiDeleteGroupRequest {
  /**
   * A group identifier or slug
   * @type {string}
   * @memberof GroupApiDeleteGroup
   */
  readonly groupId: string;
}

/**
 * Request parameters for deleteGroupFromMod operation in GroupApi.
 * @export
 * @interface GroupApiDeleteGroupFromModRequest
 */
export interface GroupApiDeleteGroupFromModRequest {
  /**
   * A group identifier or slug
   * @type {string}
   * @memberof GroupApiDeleteGroupFromMod
   */
  readonly groupId: string;

  /**
   * The group mod data to unlink
   * @type {DeleteGroupFromModRequest}
   * @memberof GroupApiDeleteGroupFromMod
   */
  readonly deleteGroupFromModRequest: DeleteGroupFromModRequest;
}

/**
 * Request parameters for deleteGroupFromPack operation in GroupApi.
 * @export
 * @interface GroupApiDeleteGroupFromPackRequest
 */
export interface GroupApiDeleteGroupFromPackRequest {
  /**
   * A group identifier or slug
   * @type {string}
   * @memberof GroupApiDeleteGroupFromPack
   */
  readonly groupId: string;

  /**
   * The group pack data to unlink
   * @type {DeleteGroupFromPackRequest}
   * @memberof GroupApiDeleteGroupFromPack
   */
  readonly deleteGroupFromPackRequest: DeleteGroupFromPackRequest;
}

/**
 * Request parameters for deleteGroupFromUser operation in GroupApi.
 * @export
 * @interface GroupApiDeleteGroupFromUserRequest
 */
export interface GroupApiDeleteGroupFromUserRequest {
  /**
   * A group identifier or slug
   * @type {string}
   * @memberof GroupApiDeleteGroupFromUser
   */
  readonly groupId: string;

  /**
   * The group user data to unlink
   * @type {DeletePackFromUserRequest}
   * @memberof GroupApiDeleteGroupFromUser
   */
  readonly deletePackFromUserRequest: DeletePackFromUserRequest;
}

/**
 * Request parameters for listGroupMods operation in GroupApi.
 * @export
 * @interface GroupApiListGroupModsRequest
 */
export interface GroupApiListGroupModsRequest {
  /**
   * A group identifier or slug
   * @type {string}
   * @memberof GroupApiListGroupMods
   */
  readonly groupId: string;

  /**
   * Search query
   * @type {string}
   * @memberof GroupApiListGroupMods
   */
  readonly search?: string;

  /**
   * Sorting column
   * @type {string}
   * @memberof GroupApiListGroupMods
   */
  readonly sort?: string;

  /**
   * Sorting order
   * @type {'asc' | 'desc'}
   * @memberof GroupApiListGroupMods
   */
  readonly order?: ListGroupModsOrderEnum;

  /**
   * Paging limit
   * @type {number}
   * @memberof GroupApiListGroupMods
   */
  readonly limit?: number;

  /**
   * Paging offset
   * @type {number}
   * @memberof GroupApiListGroupMods
   */
  readonly offset?: number;
}

/**
 * Request parameters for listGroupPacks operation in GroupApi.
 * @export
 * @interface GroupApiListGroupPacksRequest
 */
export interface GroupApiListGroupPacksRequest {
  /**
   * A group identifier or slug
   * @type {string}
   * @memberof GroupApiListGroupPacks
   */
  readonly groupId: string;

  /**
   * Search query
   * @type {string}
   * @memberof GroupApiListGroupPacks
   */
  readonly search?: string;

  /**
   * Sorting column
   * @type {string}
   * @memberof GroupApiListGroupPacks
   */
  readonly sort?: string;

  /**
   * Sorting order
   * @type {'asc' | 'desc'}
   * @memberof GroupApiListGroupPacks
   */
  readonly order?: ListGroupPacksOrderEnum;

  /**
   * Paging limit
   * @type {number}
   * @memberof GroupApiListGroupPacks
   */
  readonly limit?: number;

  /**
   * Paging offset
   * @type {number}
   * @memberof GroupApiListGroupPacks
   */
  readonly offset?: number;
}

/**
 * Request parameters for listGroupUsers operation in GroupApi.
 * @export
 * @interface GroupApiListGroupUsersRequest
 */
export interface GroupApiListGroupUsersRequest {
  /**
   * A group identifier or slug
   * @type {string}
   * @memberof GroupApiListGroupUsers
   */
  readonly groupId: string;

  /**
   * Search query
   * @type {string}
   * @memberof GroupApiListGroupUsers
   */
  readonly search?: string;

  /**
   * Sorting column
   * @type {string}
   * @memberof GroupApiListGroupUsers
   */
  readonly sort?: string;

  /**
   * Sorting order
   * @type {'asc' | 'desc'}
   * @memberof GroupApiListGroupUsers
   */
  readonly order?: ListGroupUsersOrderEnum;

  /**
   * Paging limit
   * @type {number}
   * @memberof GroupApiListGroupUsers
   */
  readonly limit?: number;

  /**
   * Paging offset
   * @type {number}
   * @memberof GroupApiListGroupUsers
   */
  readonly offset?: number;
}

/**
 * Request parameters for listGroups operation in GroupApi.
 * @export
 * @interface GroupApiListGroupsRequest
 */
export interface GroupApiListGroupsRequest {
  /**
   * Search query
   * @type {string}
   * @memberof GroupApiListGroups
   */
  readonly search?: string;

  /**
   * Sorting column
   * @type {string}
   * @memberof GroupApiListGroups
   */
  readonly sort?: string;

  /**
   * Sorting order
   * @type {'asc' | 'desc'}
   * @memberof GroupApiListGroups
   */
  readonly order?: ListGroupsOrderEnum;

  /**
   * Paging limit
   * @type {number}
   * @memberof GroupApiListGroups
   */
  readonly limit?: number;

  /**
   * Paging offset
   * @type {number}
   * @memberof GroupApiListGroups
   */
  readonly offset?: number;
}

/**
 * Request parameters for permitGroupMod operation in GroupApi.
 * @export
 * @interface GroupApiPermitGroupModRequest
 */
export interface GroupApiPermitGroupModRequest {
  /**
   * A group identifier or slug
   * @type {string}
   * @memberof GroupApiPermitGroupMod
   */
  readonly groupId: string;

  /**
   * The group mod data to permit
   * @type {PermitGroupModRequest}
   * @memberof GroupApiPermitGroupMod
   */
  readonly permitGroupModRequest: PermitGroupModRequest;
}

/**
 * Request parameters for permitGroupPack operation in GroupApi.
 * @export
 * @interface GroupApiPermitGroupPackRequest
 */
export interface GroupApiPermitGroupPackRequest {
  /**
   * A group identifier or slug
   * @type {string}
   * @memberof GroupApiPermitGroupPack
   */
  readonly groupId: string;

  /**
   * The group pack data to permit
   * @type {PermitGroupPackRequest}
   * @memberof GroupApiPermitGroupPack
   */
  readonly permitGroupPackRequest: PermitGroupPackRequest;
}

/**
 * Request parameters for permitGroupUser operation in GroupApi.
 * @export
 * @interface GroupApiPermitGroupUserRequest
 */
export interface GroupApiPermitGroupUserRequest {
  /**
   * A group identifier or slug
   * @type {string}
   * @memberof GroupApiPermitGroupUser
   */
  readonly groupId: string;

  /**
   * The group user data to permit
   * @type {PermitPackUserRequest}
   * @memberof GroupApiPermitGroupUser
   */
  readonly permitPackUserRequest: PermitPackUserRequest;
}

/**
 * Request parameters for showGroup operation in GroupApi.
 * @export
 * @interface GroupApiShowGroupRequest
 */
export interface GroupApiShowGroupRequest {
  /**
   * A group identifier or slug
   * @type {string}
   * @memberof GroupApiShowGroup
   */
  readonly groupId: string;
}

/**
 * Request parameters for updateGroup operation in GroupApi.
 * @export
 * @interface GroupApiUpdateGroupRequest
 */
export interface GroupApiUpdateGroupRequest {
  /**
   * A group identifier or slug
   * @type {string}
   * @memberof GroupApiUpdateGroup
   */
  readonly groupId: string;

  /**
   * The group data to update
   * @type {CreateGroupRequest}
   * @memberof GroupApiUpdateGroup
   */
  readonly createGroupRequest: CreateGroupRequest;
}

/**
 * GroupApi - object-oriented interface
 * @export
 * @class GroupApi
 * @extends {BaseAPI}
 */
export class GroupApi extends BaseAPI {
  /**
   *
   * @summary Attach a mod to group
   * @param {GroupApiAttachGroupToModRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof GroupApi
   */
  public attachGroupToMod(
    requestParameters: GroupApiAttachGroupToModRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return GroupApiFp(this.configuration)
      .attachGroupToMod(
        requestParameters.groupId,
        requestParameters.permitGroupModRequest,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Attach a pack to group
   * @param {GroupApiAttachGroupToPackRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof GroupApi
   */
  public attachGroupToPack(
    requestParameters: GroupApiAttachGroupToPackRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return GroupApiFp(this.configuration)
      .attachGroupToPack(
        requestParameters.groupId,
        requestParameters.permitGroupPackRequest,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Attach a user to group
   * @param {GroupApiAttachGroupToUserRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof GroupApi
   */
  public attachGroupToUser(
    requestParameters: GroupApiAttachGroupToUserRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return GroupApiFp(this.configuration)
      .attachGroupToUser(
        requestParameters.groupId,
        requestParameters.permitPackUserRequest,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Create a new group
   * @param {GroupApiCreateGroupRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof GroupApi
   */
  public createGroup(
    requestParameters: GroupApiCreateGroupRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return GroupApiFp(this.configuration)
      .createGroup(requestParameters.createGroupRequest, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Delete a specific group
   * @param {GroupApiDeleteGroupRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof GroupApi
   */
  public deleteGroup(
    requestParameters: GroupApiDeleteGroupRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return GroupApiFp(this.configuration)
      .deleteGroup(requestParameters.groupId, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Unlink a mod from group
   * @param {GroupApiDeleteGroupFromModRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof GroupApi
   */
  public deleteGroupFromMod(
    requestParameters: GroupApiDeleteGroupFromModRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return GroupApiFp(this.configuration)
      .deleteGroupFromMod(
        requestParameters.groupId,
        requestParameters.deleteGroupFromModRequest,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Unlink a pack from group
   * @param {GroupApiDeleteGroupFromPackRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof GroupApi
   */
  public deleteGroupFromPack(
    requestParameters: GroupApiDeleteGroupFromPackRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return GroupApiFp(this.configuration)
      .deleteGroupFromPack(
        requestParameters.groupId,
        requestParameters.deleteGroupFromPackRequest,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Unlink a user from group
   * @param {GroupApiDeleteGroupFromUserRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof GroupApi
   */
  public deleteGroupFromUser(
    requestParameters: GroupApiDeleteGroupFromUserRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return GroupApiFp(this.configuration)
      .deleteGroupFromUser(
        requestParameters.groupId,
        requestParameters.deletePackFromUserRequest,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Fetch all mods attached to group
   * @param {GroupApiListGroupModsRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof GroupApi
   */
  public listGroupMods(
    requestParameters: GroupApiListGroupModsRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return GroupApiFp(this.configuration)
      .listGroupMods(
        requestParameters.groupId,
        requestParameters.search,
        requestParameters.sort,
        requestParameters.order,
        requestParameters.limit,
        requestParameters.offset,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Fetch all packs attached to group
   * @param {GroupApiListGroupPacksRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof GroupApi
   */
  public listGroupPacks(
    requestParameters: GroupApiListGroupPacksRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return GroupApiFp(this.configuration)
      .listGroupPacks(
        requestParameters.groupId,
        requestParameters.search,
        requestParameters.sort,
        requestParameters.order,
        requestParameters.limit,
        requestParameters.offset,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Fetch all users attached to group
   * @param {GroupApiListGroupUsersRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof GroupApi
   */
  public listGroupUsers(
    requestParameters: GroupApiListGroupUsersRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return GroupApiFp(this.configuration)
      .listGroupUsers(
        requestParameters.groupId,
        requestParameters.search,
        requestParameters.sort,
        requestParameters.order,
        requestParameters.limit,
        requestParameters.offset,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Fetch all available groups
   * @param {GroupApiListGroupsRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof GroupApi
   */
  public listGroups(
    requestParameters: GroupApiListGroupsRequest = {},
    options?: RawAxiosRequestConfig,
  ) {
    return GroupApiFp(this.configuration)
      .listGroups(
        requestParameters.search,
        requestParameters.sort,
        requestParameters.order,
        requestParameters.limit,
        requestParameters.offset,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Update mod perms for group
   * @param {GroupApiPermitGroupModRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof GroupApi
   */
  public permitGroupMod(
    requestParameters: GroupApiPermitGroupModRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return GroupApiFp(this.configuration)
      .permitGroupMod(
        requestParameters.groupId,
        requestParameters.permitGroupModRequest,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Update pack perms for group
   * @param {GroupApiPermitGroupPackRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof GroupApi
   */
  public permitGroupPack(
    requestParameters: GroupApiPermitGroupPackRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return GroupApiFp(this.configuration)
      .permitGroupPack(
        requestParameters.groupId,
        requestParameters.permitGroupPackRequest,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Update user perms for group
   * @param {GroupApiPermitGroupUserRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof GroupApi
   */
  public permitGroupUser(
    requestParameters: GroupApiPermitGroupUserRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return GroupApiFp(this.configuration)
      .permitGroupUser(
        requestParameters.groupId,
        requestParameters.permitPackUserRequest,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Fetch a specific group
   * @param {GroupApiShowGroupRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof GroupApi
   */
  public showGroup(
    requestParameters: GroupApiShowGroupRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return GroupApiFp(this.configuration)
      .showGroup(requestParameters.groupId, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary Update a specific group
   * @param {GroupApiUpdateGroupRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof GroupApi
   */
  public updateGroup(
    requestParameters: GroupApiUpdateGroupRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return GroupApiFp(this.configuration)
      .updateGroup(
        requestParameters.groupId,
        requestParameters.createGroupRequest,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }
}

/**
 * @export
 */
export const ListGroupModsOrderEnum = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type ListGroupModsOrderEnum =
  (typeof ListGroupModsOrderEnum)[keyof typeof ListGroupModsOrderEnum];
/**
 * @export
 */
export const ListGroupPacksOrderEnum = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type ListGroupPacksOrderEnum =
  (typeof ListGroupPacksOrderEnum)[keyof typeof ListGroupPacksOrderEnum];
/**
 * @export
 */
export const ListGroupUsersOrderEnum = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type ListGroupUsersOrderEnum =
  (typeof ListGroupUsersOrderEnum)[keyof typeof ListGroupUsersOrderEnum];
/**
 * @export
 */
export const ListGroupsOrderEnum = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type ListGroupsOrderEnum =
  (typeof ListGroupsOrderEnum)[keyof typeof ListGroupsOrderEnum];
